# Delete the '-template' in the file name before starting the app
remote_host: <FILL_HERE>
local_host: <FILL_HERE>

spring:
  datasource:
    url: <FILL_HERE>
    username: <FILL_HERE>
    password: <FILL_HERE>
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: <FILL_HERE>
            clientSecret: <FILL_HERE>
            redirectUriTemplate: <FILL_HERE>
            scope:
              - email
              - profile
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 20MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: <FILL_HERE>
    password: <FILL_HERE>
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true


app:
  auth:
    tokenSecret: <FILL_HERE>
    tokenExpirationMsec: <FILL_HERE>
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - https://bitmovie.herokuapp.com/oauth2/redirect
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
cloudinary:
  default_avatar: <FILL_HERE>
  cloud_name: <FILL_HERE>
  api_key: <FILL_HERE>
  api_secret: <FILL_HERE>

omdb_api_key: <FILL_HERE>
tmdb_api_key: <FILL_HERE>
tmdbUrl: https://api.themoviedb.org/3/
omdbUrl: http://www.omdbapi.com/
